"""add_stripe_processed_events_table

Revision ID: 040177e014ea
Revises: a1b2c3d4e5f6
Create Date: 2026-04-11 23:55:25.494327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040177e014ea'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_processed_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stripe_processed_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_processed_events_stripe_event_id'), ['stripe_event_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_processed_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_processed_events_stripe_event_id'))

    op.drop_table('stripe_processed_events')
    # ### end Alembic commands ###
