"""add bot_logs table

Revision ID: 0da70cea5aa9
Revises: aa49d9caa942
Create Date: 2026-03-18 16:35:22.968611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da70cea5aa9'
down_revision = 'aa49d9caa942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_logs_bot_id'), ['bot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_logs_bot_id'))

    op.drop_table('bot_logs')
    # ### end Alembic commands ###
